{% set name = "timm" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1d4b55778e74ace21f39a1461c7075632ed5895532d11b53a85d1bedac0c5d77

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - torchvision
    - pytorch >=1.4

test:
  imports:
    - timm
    - timm.data
    - timm.loss
    - timm.models
    - timm.models.layers
    - timm.optim
    - timm.scheduler

about:
  home: https://github.com/rwightman/pytorch-image-models
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: (Unofficial) PyTorch Image Models
  doc_url: https://pypi.org/project/timm/
  dev_url: https://github.com/rwightman/pytorch-image-models

extra:
  recipe-maintainers:
    - ndmaxar
    - oblute
    - rluria14
