{% set name = "timm" %}
{% set version = "0.9.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9121d1cf320f7f32490d893340fd33117bda0a0270eb8282dfd52ae5fd3e1af6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  # torchvision is not available on s390x
  skip: True  # [py<37 or s390x]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - pytorch >=1.7
    - torchvision
    - pyyaml
    - huggingface_hub
    - safetensors

test:
  imports:
    - timm
    - timm.data
    - timm.loss
    - timm.models
    - timm.models.layers
    - timm.optim
    - timm.scheduler
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rwightman/pytorch-image-models
  description: |
    timm is a library containing SOTA computer vision models, layers, utilities,
    optimizers, schedulers, data-loaders, augmentations, and training/evaluation scripts.
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: (Unofficial) PyTorch Image Models
  doc_url: https://pypi.org/project/timm/
  dev_url: https://github.com/rwightman/pytorch-image-models

extra:
  recipe-maintainers:
    - deepsworld
    - ndmaxar
    - oblute
    - rluria14
    - thewchan
